<template>
  <h1
    class="text-2xl
           sm:text-3xl
           font-bold
           text-gray-900
           dark:text-white
           inline-block
           pb-2
           sm:pb-4
           md:pb-5
           capitalize
           relative
           mb-8
           after:absolute
           after:bottom-0
           after:left-0
           after:w-8
           after:sm:w-10
           after:h-1
           after:rounded-2xl
           after:bg-primary
    "
  >
    <slot />
  </h1>
</template>
